import { Inter } from "next/font/google";
import "./globals.css";
import "./../public/css/bootstrap.min.css";
import Head from "next/head";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FoodPark || Restaurant Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className={inter.className}>{children}</body>
      <Script src="/js/jquery-3.6.0.min.js" />
      <Script src="/js/bootstrap.bundle.min.js" />
      <Script src="/js/Font-Awesome.js" />
      <Script src="/js/slick.min.js" />
      <Script src="/js/isotope.pkgd.min.js" />
      <Script src="/js/simplyCountdown.js" />
      <Script src="/js/jquery.waypoints.min.js" />
      <Script src="/js/jquery.countup.min.js" />
      <Script src="/js/jquery.nice-select.min.js" />
      <Script src="/js/venobox.min.js" />
      <Script src="/js/sticky_sidebar.js" />
      <Script src="/js/wow.min.js" />
      <Script src="/js/jquery.exzoom.js" />

      <Script src="/js/main.js" />
    </html>
  );
}
