import "./globals.css";
import "./../public/css/bootstrap.min.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./../public/css/all.min.css";
import "./../public/css/animate.css";
import "./../public/css/responsive.css";
import "./../public/css/nice-select.css";
import "./../public/css/spacing.css";
import "./../public/css/venobox.min.css";
import Head from "next/head";
import Script from "next/script";
import TopBar from "./components/TopBar";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";
import ScrollTop from "./components/ScrollTop";

export const metadata = {
  title: "FoodPark || Restaurant Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      {/* <Script src="/js/jquery-3.6.0.min.js" /> */}
      <Script src="/js/bootstrap.bundle.min.js" />
      <Script src="/js/Font-Awesome.js" />
      <Script src="/js/isotope.pkgd.min.js" />
      {/* <Script src="/js/simplyCountdown.js" /> */}
      <Script src="/js/venobox.min.js" />
      <Script type="module" src="/js/sticky_sidebar.js" />
      <Script src="/js/wow.min.js" />
      {/* <Script src="/js/jquery.waypoints.min.js" /> */}
      {/* <Script src="/js/jquery.countup.min.js" /> */}
      {/* <Script src="/js/jquery.nice-select.min.js" /> */}
      {/* <Script src="/js/jquery.exzoom.js" /> */}

      <Script src="/js/main.js" />
      <Script src="/js/scroll-up.js" />
      <body className={``}>
        <TopBar />
        <NavBar />
        {children}
        <ScrollTop />
        <Footer />
      </body>
    </html>
  );
}
